In [2]:
import sys
import numpy as np
import tensorflow as tf
from datetime import datetime

In [10]:
device_name="/gpu:0"
#device_name="/cpu:0"

shape=(int(10000),int(10000))

with tf.device(device_name):
    random_matrix = tf.random_uniform(shape=shape, minval=0, maxval=1)
    dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
    sum_operation = tf.reduce_sum(dot_operation)

startTime = datetime.now()
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
        result = session.run(dot_operation)
        #result = session.run(sum_operation)
        print(result)

print("\n" * 2)
print("Shape:", shape, "Device:", device_name)
print("Time taken:", datetime.now() - startTime)

print("\n" * 2)


[[3369.473  2530.09   2521.7864 ... 2515.2507 2537.422  2503.6934]
 [2530.09   3360.0183 2511.4233 ... 2504.335  2517.273  2480.953 ]
 [2521.7864 2511.4233 3331.1047 ... 2489.4678 2507.937  2471.2534]
 ...
 [2515.2507 2504.335  2489.4678 ... 3310.2205 2494.7012 2477.1274]
 [2537.422  2517.273  2507.937  ... 2494.7012 3356.941  2501.6643]
 [2503.6934 2480.953  2471.2534 ... 2477.1274 2501.6643 3301.3962]]



Shape: (10000, 10000) Device: /gpu:0
Time taken: 0:00:01.778264



